import assert from 'node:assert/strict';
import {testStorefrontFeatures} from './storefront-features.mjs';
import {testClientSession} from './client-session.mjs';
import {readFile,readdir,mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const wranglerRequire=createRequire(require.resolve('wrangler/package.json'));
const {build}=wranglerRequire('esbuild');
const temp=await mkdtemp(join(tmpdir(),'gura-test-'));
await build({entryPoints:['tests/api-worker.ts'],outfile:join(temp,'worker.mjs'),bundle:true,format:'esm',platform:'node',tsconfig:'tsconfig.json',plugins:[{name:'offline-storage',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:resolve('tests/offline-env.mjs')}));}}]});
const runtime=await import(pathToFileURL(join(temp,'worker.mjs')).href);
const mf={dispatchFetch:(url,options)=>runtime.default.fetch(new Request(url,options)),getD1Database:async()=>runtime.env.DB,dispose:async()=>runtime.env.DB.close()};
let passed=0;
const check=(condition,message)=>{assert.ok(condition,message);passed++;console.log('PASS '+message);};
async function call(path,method='GET',data,cookie='',extra={}){const res=await mf.dispatchFetch('https://gura.test/api/'+path,{method,headers:{...(method!=='GET'?{'x-gura-action':'1','origin':'https://gura.test'}:{}),...(cookie?{cookie}:{}),...(data&&!(data instanceof FormData)?{'content-type':'application/json'}:{}),...extra},body:data?(data instanceof FormData?data:JSON.stringify(data)):undefined});const json=await res.json().catch(()=>({}));return {status:res.status,data:json,cookie:res.headers.get('set-cookie')?.split(';')[0]||'',headers:res.headers};}
try{
 const database=await mf.getD1Database('DB');for(const file of (await readdir('drizzle')).filter(name=>/^\d+.*\.sql$/.test(name)).sort()){const migration=await readFile('drizzle/'+file,'utf8');for(const sql of migration.split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await database.prepare(sql).run();}
 const initial=await call('bootstrap');check(initial.data.needsOwner===true&&initial.data.user===null,'Fresh shop has no owner or signed-in user');check((await call('products')).data.products.length===0,'Catalog starts completely empty');
 const owner={name:'Owner test',email:'owner@example.test',password:'1234567890',setup_key:'test-owner-setup-code'};
 check((await call('auth/owner-setup','POST',{...owner,setup_key:'wrong'})).status===403,'Owner setup rejects incorrect setup code');
 check((await call('auth/owner-setup','POST',{...owner,password:'123456789'})).status===400,'Owner password rejects 9 characters');
 const admin=await call('auth/owner-setup','POST',owner);check(admin.status===201&&admin.data.user.role==='admin','Owner password accepts exactly 10 characters');
 check(/HttpOnly/.test(admin.headers.get('set-cookie'))&&/Secure/.test(admin.headers.get('set-cookie')),'Sessions use secure HttpOnly cookies');
 check((await call('auth/owner-setup','POST',{...owner,email:'other@example.test'})).status===409,'Second owner setup is blocked');
 check((await call('auth/register','POST',{name:'Customer',email:'customer@example.test',password:'12345'})).status===400,'Customer password rejects 5 characters');
 const customer=await call('auth/register','POST',{name:'Customer',email:'customer@example.test',password:'123456',role:'admin'});check(customer.status===201&&customer.data.user.role==='customer','Six-character customer password accepted; supplied admin role ignored');
 const customer2=await call('auth/register','POST',{name:'Customer two',email:'customer2@example.test',password:'abcdef'});
 check((await call('admin/products','GET',null,customer.cookie)).status===403,'Customer cannot read owner product controls');
 check((await call('admin/products','POST',{},customer.cookie)).status===403,'Customer cannot create products');
 check((await call('admin/overview')).status===401,'Anonymous visitors cannot use owner APIs');
 check((await call('profile','PATCH',{},customer.cookie,{origin:'https://attacker.test'})).status===403,'Cross-origin changes are rejected');
 await testStorefrontFeatures(call,database,check,admin,customer);
 const input={name:'Temporary test item',description:'Only exists in isolated test storage',brand:'Test brand',category:'Food',price:'120.50',unit:'pack',quantity:1,active:true};
 check((await call('admin/products','POST',{...input,price:'-1'},admin.cookie)).status===400,'Negative product prices are rejected');
 check((await call('admin/products','POST',{...input,quantity:-1},admin.cookie)).status===400,'Negative stock is rejected');
 const created=await call('admin/products','POST',input,admin.cookie);check(created.status===201&&created.data.price===12050,'Owner controls price, unit, and stock');const id=created.data.id;
 const switched=await call('auth/login','POST',{email:'customer@example.test',password:'123456'});
 const staleSave=await call('admin/products','POST',input,switched.cookie,{'x-gura-user':admin.data.user.id});
 check(staleSave.status===409&&staleSave.data.code==='SESSION_CHANGED','Customer login in another tab rejects a stale owner save with an actionable session error');
 check((await call('admin/products','GET',null,admin.cookie)).data.length===1,'Rejected stale save creates no product');
 const customerAsOwner=await call('admin/products','POST',input,customer.cookie,{'x-gura-user':customer.data.user.id});
 check(customerAsOwner.status===403&&customerAsOwner.data.code==='OWNER_REQUIRED','Account synchronization cannot grant customers owner permissions');
 const signedBackIn=await call('auth/login','POST',{email:owner.email,password:owner.password});
 const ownerAgain=await call('admin/products','GET',null,signedBackIn.cookie,{'x-gura-user':admin.data.user.id});
 check(ownerAgain.status===200&&ownerAgain.data.length===1,'Signing back into the owner account restores product access');
 const expired=await call('admin/products','POST',input,'',{'x-gura-user':admin.data.user.id});
 check(expired.status===401&&expired.data.code==='SESSION_EXPIRED','Expired sessions request sign-in rather than misidentifying the owner as a customer');
 const staleLogout=await call('auth/logout','POST',{},switched.cookie,{'x-gura-user':admin.data.user.id});
 check(staleLogout.status===409&&(await call('profile','GET',null,switched.cookie)).status===200,'An old tab cannot accidentally sign out the newly selected account');
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jCGQAAAAASUVORK5CYII=','base64');
 const bad=new FormData();bad.set('file',new Blob(['<script>alert(1)</script>'],{type:'image/png'}),'fake.png');check((await call('admin/products/'+id+'/photos','POST',bad,admin.cookie)).status===400,'Image upload checks file signature, not filename');
 for(let i=0;i<13;i++){const fd=new FormData();fd.set('file',new Blob([png],{type:'image/png'}),'photo-'+i+'.png');assert.equal((await call('admin/products/'+id+'/photos','POST',fd,admin.cookie)).status,201);}
 let detail=(await call('products/'+id)).data;check(detail.images.length===13,'Gallery returns every uploaded photo (13 verified)');
 await call('admin/photos/'+detail.images[12].id,'PATCH',{},admin.cookie);detail=(await call('products/'+id)).data;check(detail.image===detail.images[0].object_key,'Chosen cover is first in gallery and product card');
 const img=await mf.dispatchFetch('https://gura.test/api/media/'+detail.image);check(img.status===200&&img.headers.get('content-type')==='image/png','Uploaded image bytes can be retrieved');
 const query=await call('products?q=Temporary&category=Food');check(query.status===200&&query.data.products.length===1,'Search and category filtering query real products');
 await call('cart','POST',{product_id:id,quantity:1},customer.cookie);await call('cart','POST',{product_id:id,quantity:1},customer2.cookie);
 check((await call('cart','POST',{product_id:id,quantity:1},customer.cookie)).status===409,'Cart cannot exceed available stock');
 const checkout={recipient:'Recipient',address:'Test delivery address',phone:'000000000'};const request1=crypto.randomUUID(),request2=crypto.randomUUID();
 const results=await Promise.all([call('orders','POST',{...checkout,request_id:request1},customer.cookie),call('orders','POST',{...checkout,request_id:request2},customer2.cookie)]);
 check(results.filter(x=>x.status===201).length===1&&results.filter(x=>x.status===409).length===1,'Concurrent checkouts cannot oversell the last unit');
 const index=results.findIndex(x=>x.status===201),winner=index===0?customer:customer2,loser=index===0?customer2:customer;const orderId=results[index].data.id,requestId=index===0?request1:request2;
 check((await call('products/'+id)).data.quantity===0,'Successful checkout decrements stock exactly once');
 const retry=await call('orders','POST',{...checkout,request_id:requestId},winner.cookie);check(retry.data.id===orderId,'Checkout retry is idempotent');
 check((await call('orders','GET',null,loser.cookie)).data.length===0,'Customer cannot see another customer’s order');
 const order=(await call('orders','GET',null,winner.cookie)).data[0];check(order.total===12050&&order.paid===0,'Order snapshots server price and starts unpaid');
 check((await call('history','GET',null,winner.cookie)).data.brands.length===0,'Unpaid order is not counted as a purchased brand');
 await call('admin/orders/'+orderId,'PATCH',{status:'Confirmed',paid:true,delivery_date:'2026-09-20'},admin.cookie);
 check((await call('history','GET',null,winner.cookie)).data.brands[0].purchases===1,'Paid purchases drive personal top-brand ranking');
 check((await call('admin/orders/'+orderId,'PATCH',{status:'Cancelled',paid:false},admin.cookie)).status===400,'Paid order must have refund recorded before cancellation');
 await call('admin/orders/'+orderId,'PATCH',{status:'Confirmed',paid:false,delivery_date:''},admin.cookie);
 await call('admin/orders/'+orderId,'PATCH',{status:'Cancelled',paid:false,delivery_date:''},admin.cookie);
 await call('admin/orders/'+orderId,'PATCH',{status:'Cancelled',paid:false,delivery_date:''},admin.cookie);
 check((await call('products/'+id)).data.quantity===1,'Cancelling twice restores stock only once');
 check((await call('admin/products/'+id,'PATCH',{...input,version:1},admin.cookie)).status===409,'Stale owner edits cannot overwrite changed stock');
 const current=(await call('admin/products/'+id,'GET',null,admin.cookie)).data;
 await call('admin/products/'+id,'PATCH',{...input,active:false,version:current.version},admin.cookie);
 check((await call('products/'+id)).status===404,'Hidden products are unavailable to customers');
 check((await call('profile/password','POST',{current_password:'1234567890',password:'123456789'},admin.cookie)).status===400,'Owner password minimum also enforced during changes');
 const before=await database.prepare('SELECT password FROM users WHERE id=?').bind(customer.data.user.id).first();check(before.password!=='123456'&&before.password.startsWith('pbkdf2$'),'Database stores salted password hashes, never plaintext');
 const logout=await call('auth/logout','POST',{},customer.cookie);check(logout.status===200&&(await call('profile','GET',null,customer.cookie)).status===401,'Sign-out invalidates the server session');
 await build({entryPoints:['lib/client-api.ts'],outfile:join(temp,'client.mjs'),bundle:true,format:'esm',platform:'node',tsconfig:'tsconfig.json'});
 await testClientSession(await import(pathToFileURL(join(temp,'client.mjs')).href),check);
 console.log('\n'+passed+' checks passed. Test database and files are isolated and discarded.');
}finally{await mf.dispose();await rm(temp,{recursive:true,force:true});}
