import {sqliteTable,text,integer,uniqueIndex,index,primaryKey,check} from 'drizzle-orm/sqlite-core';
import {sql} from 'drizzle-orm';
export const users=sqliteTable('users',{
 id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull().unique(),password:text('password').notNull(),role:text('role').notNull().default('customer'),phone:text('phone').notNull().default(''),avatar:text('avatar'),recipient:text('recipient').notNull().default(''),address:text('address').notNull().default(''),delivery_phone:text('delivery_phone').notNull().default(''),country:text('country').notNull().default('Uganda'),language:text('language').notNull().default('en'),notifications:integer('notifications').notNull().default(1),gold_requested:integer('gold_requested').notNull().default(0),created_at:integer('created_at').notNull()
},t=>[uniqueIndex('one_shop_owner').on(t.role).where(sql`${t.role} = 'admin'`),check('user_role',sql`${t.role} IN ('admin','customer')`)]);
export const sessions=sqliteTable('sessions',{token:text('token').primaryKey(),user_id:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),expires:integer('expires').notNull()},t=>[index('sessions_user').on(t.user_id)]);
export const loginLimits=sqliteTable('login_limits',{key:text('key').primaryKey(),attempts:integer('attempts').notNull(),expires:integer('expires').notNull()});
export const products=sqliteTable('products',{
 id:text('id').primaryKey(),name:text('name').notNull(),description:text('description').notNull().default(''),brand:text('brand').notNull().default(''),category:text('category').notNull(),price:integer('price').notNull(),unit:text('unit').notNull(),quantity:integer('quantity').notNull(),active:integer('active').notNull().default(0),version:integer('version').notNull().default(1),cover_image:text('cover_image'),sort_key:integer('sort_key').notNull(),created_at:integer('created_at').notNull()
},t=>[check('stock_nonnegative',sql`${t.quantity} >= 0`),check('price_nonnegative',sql`${t.price} >= 0`),index('products_browse').on(t.active,t.sort_key),index('products_category').on(t.category,t.active)]);
export const photos=sqliteTable('photos',{id:text('id').primaryKey(),product_id:text('product_id').notNull().references(()=>products.id,{onDelete:'cascade'}),object_key:text('object_key').notNull(),content_type:text('content_type').notNull(),position:integer('position').notNull()},t=>[index('photos_product').on(t.product_id,t.position)]);
export const cart=sqliteTable('cart',{user_id:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),product_id:text('product_id').notNull().references(()=>products.id,{onDelete:'cascade'}),quantity:integer('quantity').notNull()},t=>[primaryKey({columns:[t.user_id,t.product_id]}),check('cart_positive',sql`${t.quantity} > 0`)]);
export const orders=sqliteTable('orders',{id:text('id').primaryKey(),user_id:text('user_id').references(()=>users.id,{onDelete:'set null'}),request_id:text('request_id').notNull().unique(),status:text('status').notNull().default('Pending'),total:integer('total').notNull().default(0),delivery_fee:integer('delivery_fee').notNull(),currency:text('currency').notNull(),paid:integer('paid').notNull().default(0),delivery_date:text('delivery_date').notNull().default(''),recipient:text('recipient').notNull(),address:text('address').notNull(),phone:text('phone').notNull(),created_at:integer('created_at').notNull()},t=>[index('orders_user_date').on(t.user_id,t.created_at)]);
export const orderItems=sqliteTable('order_items',{id:text('id').primaryKey(),order_id:text('order_id').notNull().references(()=>orders.id,{onDelete:'cascade'}),product_id:text('product_id').notNull().references(()=>products.id),name:text('name').notNull(),brand:text('brand').notNull(),price:integer('price').notNull(),unit:text('unit').notNull(),quantity:integer('quantity').notNull(),image:text('image')},t=>[index('items_order').on(t.order_id),check('item_positive',sql`${t.quantity} > 0`)]);
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
