'use client';
import React,{useEffect,useState} from 'react';
import {Store,LayoutDashboard,Package,ShoppingBag,Users,Settings,Plus,ArrowLeft,ArrowRight,Upload,ImageIcon,Trash2,Check,Crown,AlertTriangle,LogOut} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarFooter,SidebarInset,SidebarTrigger} from '@/components/ui/sidebar';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Switch} from '@/components/ui/switch';
import {CATEGORIES,STATUSES,Product,Order,money} from '@/lib/catalog';
import {api,go,useLoad,useShop,Action,Form,Field,SelectField,Empty,Loading,Photo,Status,PageTitle,Brand} from './shop';
import {toast} from 'sonner';
import ProductCategoryFields from './product-category-fields';
import AdminPromotions from './admin-promotions';
const menu=[['','Overview',LayoutDashboard],['products','Products',Package],['orders','Orders',ShoppingBag],['customers','Customers',Users],['promotions','Promotions',ImageIcon],['settings','Shop settings',Settings]] as const;
export default function Admin({route}:{route:string}){const {user,setAuth,bootstrap}=useShop();const section=route.split('/')[1]||'',id=route.split('/')[2];if(!user||user.role!=='admin')return <main className="page-content"><Brand/><Empty icon={Store} title="Owner sign-in required" action={<><Button onClick={()=>setAuth('login')}>Sign in</Button><Button variant="outline" onClick={()=>go('home')}>Back to shop</Button></>}>{user?<>You are signed in as <strong>{user.email}</strong>, a customer account. </>:null}Sign in with the email used when you created the shop owner account to manage products and orders.</Empty></main>;
 return <SidebarProvider className="admin-shell"><Sidebar className="admin-sidebar"><SidebarHeader><Brand/></SidebarHeader><SidebarContent><SidebarMenu>{menu.map(([key,label,Icon])=><SidebarMenuItem key={key}><SidebarMenuButton isActive={section===key} onClick={()=>go('admin'+(key?'/'+key:''))}><Icon/><span>{label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><SidebarMenuButton onClick={()=>go('home')}><Store/> View shop <ArrowRight/></SidebarMenuButton><div className="owner-label"><strong>{user.name.split(' ')[0]}</strong><span>Shop owner</span><small style={{overflowWrap:'anywhere'}}>{user.email}</small></div><Action variant="ghost" onClick={async()=>{await api('auth/logout','POST',{});await bootstrap();go('home');}}><LogOut/> Sign out</Action></SidebarFooter></Sidebar><SidebarInset><header className="admin-header"><SidebarTrigger/><span>GURA / Owner workspace</span><Button variant="outline" onClick={()=>go('home')}>View shop <ArrowRight/></Button></header><main className="admin-main" key={route}>{section==='products'?(id?<ProductEditor id={id}/>:<Products/>):section==='orders'?<AdminOrders/>:section==='customers'?<Customers/>:section==='promotions'?<AdminPromotions/>:section==='settings'?<ShopSettings/>:<Overview/>}</main></SidebarInset></SidebarProvider>;
}
function Overview(){const {settings,revision}=useShop(),r=useLoad<any>('admin/overview',revision);if(!r.data)return <Loading error={r.error} retry={r.reload}/>;const d=r.data;return <><PageTitle title="Store overview"><Button onClick={()=>go('admin/products/new')}><Plus/> Add product</Button></PageTitle><p className="muted mb">Everything you need to run your shop.</p><div className="stats-grid">{[['Sales received',money(d.revenue,settings.currency)],['Open orders',d.open_orders||0],['Products',d.products],['Customers',d.customers]].map(([label,value])=><div className="stat-card" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{!d.products?<div className="panel onboarding"><Empty icon={Store} title="Your shop. Your products." action={<Button onClick={()=>go('admin/products/new')}><Plus/> Add your first product</Button>}>Start with a product name, price, selling unit, stock quantity, and your photos.</Empty></div>:<section className="panel"><div className="between"><h2>Stock alerts</h2><button className="text-link" onClick={()=>go('admin/products')}>Manage products <ArrowRight size={16}/></button></div>{d.low_stock.length?d.low_stock.map((p:Product)=><button className="stock-row" key={p.id} onClick={()=>go('admin/products/'+p.id)}><Photo src={p.image} alt={p.name}/><span>{p.name}</span><b className="danger">{p.quantity} {p.unit} left</b><ArrowRight size={18}/></button>):<p className="muted">No low-stock products.</p>}</section>}</>;}
function Products(){const {settings,revision}=useShop(),r=useLoad<Product[]>('admin/products',revision),[query,setQuery]=useState('');return <><PageTitle title="Products"><Button onClick={()=>go('admin/products/new')}><Plus/> Add product</Button></PageTitle><input className="filter-input" placeholder="Find a product" aria-label="Find a product" value={query} onChange={e=>setQuery(e.target.value)}/>{r.loading||r.error?<Loading error={r.error} retry={r.reload}/>:!r.data?.length?<Empty title="No products added yet" action={<Button onClick={()=>go('admin/products/new')}>Add product</Button>}>Your catalog starts empty. Add the products you want to sell.</Empty>:<div className="panel table-panel"><Table><TableHeader><TableRow>{['Product','Price / unit','Stock','Visibility','Photos',''].map((h,i)=><TableHead key={i}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{r.data.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())).map(p=><TableRow key={p.id}><TableCell><div className="table-product"><Photo src={p.image} alt={p.name}/><div><strong>{p.name}</strong><small>{p.category}</small></div></div></TableCell><TableCell>{money(p.price,settings.currency)} / {p.unit}</TableCell><TableCell className={p.quantity<=5?'danger':''}>{p.quantity}</TableCell><TableCell><Status value={p.active?'Published':'Hidden'}/></TableCell><TableCell>{p.image_count}</TableCell><TableCell><Button variant="outline" onClick={()=>go('admin/products/'+p.id)}>Edit</Button></TableCell></TableRow>)}</TableBody></Table></div>}</>;}
function ProductEditor({id}:{id:string}){const r=useLoad<Product>(id==='new'?null:'admin/products/'+id),{settings,refresh}=useShop();const [saved,setSaved]=useState<Product|null>(null),[files,setFiles]=useState<File[]>([]),[progress,setProgress]=useState(''),[active,setActive]=useState(false),[busy,setBusy]=useState(false);const p=saved||r.data;
 useEffect(()=>{if(r.data)setActive(!!r.data.active);},[r.data]);
 if(id!=='new'&&!p)return <Loading error={r.error} retry={r.reload}/>;
 const reload=async()=>{if(p)setSaved(await api('admin/products/'+p.id));};
 return <><PageTitle title={id==='new'?'Add product':'Edit product'} back="admin/products"/><div className="editor-grid"><section className="panel"><Form submit={active?'Save and publish product':'Save hidden product'} onSave={async(b:any)=>{
 setBusy(true);setProgress('Saving product details…');try{const data={...b,quantity:Number(b.quantity),active:false};let current=await api('admin/products'+(p?'/'+p.id:''),p?'PATCH':'POST',{...data,...(p?{version:p.version}:{})});setSaved(current);const failed:File[]=[];const errors:string[]=[];
 for(let i=0;i<files.length;i++){setProgress(`Uploading photo ${i+1} of ${files.length}…`);const fd=new FormData();fd.append('file',files[i]);try{current=await api('admin/products/'+current.id+'/photos','POST',fd);setSaved(current);}catch(e:any){failed.push(files[i]);errors.push(files[i].name+': '+e.message);if(['SESSION_EXPIRED','SESSION_CHANGED','OWNER_REQUIRED'].includes(e.code)){failed.push(...files.slice(i+1));break;}}}
 setFiles(failed);if(failed.length){setProgress(`${files.length-failed.length} photos uploaded. Product saved as hidden. Select Save to retry failed photos.`);throw new Error(errors.join('\n'));}
 current=await api('admin/products/'+current.id,'PATCH',{...data,active,version:current.version});setSaved(current);setProgress('Saved successfully');refresh();toast.success(active?'Product published':'Product saved as hidden');go('admin/products');
 }catch(error){setProgress(value=>value.includes('Product saved as hidden.')?value:'');throw error;}finally{setBusy(false);}
 }}><Field label="Product name" name="name" defaultValue={p?.name} maxLength={160} required/><ProductCategoryFields category={p?.category} subcategory={p?.subcategory}/><Field label="Brand (optional)" name="brand" defaultValue={p?.brand} maxLength={100}/><label className="field"><span>Description</span><textarea name="description" defaultValue={p?.description} rows={5} maxLength={10000}/></label><div className="form-pair"><Field label={'Price ('+settings.currency+')'} name="price" type="number" inputMode="decimal" min="0" step="0.01" defaultValue={p?String(p.price/100):''} required/><Field label="Selling unit" name="unit" placeholder="e.g. piece, kg, bottle, pack" defaultValue={p?.unit} maxLength={40} required/></div><Field label="Stock quantity (number of units)" name="quantity" type="number" inputMode="numeric" min="0" step="1" defaultValue={p?.quantity??0} required/><div className="between"><div><strong>Publish in the shop</strong><p className="muted">Hidden products remain in your owner dashboard.</p></div><Switch aria-label="Publish in the shop" checked={active} onCheckedChange={setActive}/></div><label className="upload-zone"><Upload size={28}/><strong>Choose product photos</strong><span>Add as many as you need. JPG, PNG, WebP, GIF or AVIF; up to 20 MB each.</span><input type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif,image/avif" disabled={busy} onChange={e=>{setFiles(prev=>[...prev,...Array.from(e.target.files||[])]);e.target.value='';}}/></label>{files.length>0&&<div className="selected-files"><strong>{files.length} photo(s) selected</strong>{files.map((f,i)=><div key={i}><span>{f.name}</span><Button type="button" variant="ghost" size="icon" disabled={busy} aria-label={'Remove '+f.name+' from upload'} onClick={()=>setFiles(prev=>prev.filter((_,j)=>j!==i))}><Trash2 size={16}/></Button></div>)}</div>}{progress&&<p className="save-progress" role="status">{progress}</p>}</Form></section><aside><section className="panel"><h2>Product photos</h2><p className="muted">Customers swipe left and right through these photos. The cover appears in the shop.</p>{p?.images?.length?<div className="owner-photo-grid">{p.images.map((photo,i)=><div key={photo.id}><Photo src={photo.object_key} alt={'Product photo '+(i+1)}/><div><Action disabled={busy} variant="outline" onClick={async()=>{await api('admin/photos/'+photo.id,'PATCH',{});await reload();toast.success('Cover photo updated');}}>{i===0?<><Check/> Cover</>:'Set cover'}</Action><Action disabled={busy} variant="ghost" aria-label={'Remove photo '+(i+1)} onClick={async()=>{await api('admin/photos/'+photo.id,'DELETE');await reload();}}><Trash2/></Action></div></div>)}</div>:<Empty icon={ImageIcon} title="No photos yet">Your uploaded product photos will appear here after saving.</Empty>}</section>{p&&<p className="muted">Stock and prices are checked again when customers place an order.</p>}</aside></div></>;}
function AdminOrders(){const {revision,refresh}=useShop(),r=useLoad<Order[]>('admin/orders',revision),[filter,setFilter]=useState('All');return <><PageTitle title="Orders"/><div className="filter-row">{['All','Pending','On the way','Delivered','Cancelled'].map(s=><Button key={s} variant={filter===s?'default':'outline'} onClick={()=>setFilter(s)}>{s}</Button>)}</div>{r.loading||r.error?<Loading error={r.error} retry={r.reload}/>:!r.data?.length?<Empty title="No orders yet">Customer orders will appear here when they check out.</Empty>:<div className="admin-orders">{r.data.filter(o=>filter==='All'||o.status===filter).map(o=><AdminOrder key={o.id+'-'+o.status+'-'+o.paid+'-'+o.delivery_date} order={o}/>)}</div>}</>;}
function AdminOrder({order:o}:{order:Order}){const {refresh}=useShop(),[paid,setPaid]=useState(!!o.paid);return <section className="panel"><div className="between"><h2>#{o.id.slice(0,8).toUpperCase()}</h2><Status value={o.status}/></div><p className="muted">{new Date(o.created_at).toLocaleString()}</p><div className="admin-order-items">{o.items.map(i=><div className="table-product" key={i.id}><Photo src={i.image} alt={i.name}/><span>{i.name} · {i.quantity} {i.unit}</span><strong>{money(i.price*i.quantity,o.currency)}</strong></div>)}</div><p><strong>{o.recipient}</strong><br/>{o.address}<br/>{o.phone}</p><div className="between mb"><span>Order total (including delivery)</span><strong>{money(o.total,o.currency)}</strong></div><Form submit="Update order" onSave={async(b:any)=>{await api('admin/orders/'+o.id,'PATCH',{...b,paid});refresh();toast.success('Order updated');}}><div className="form-pair"><SelectField name="status" label="Order status" defaultValue={o.status}>{STATUSES.map(s=><option key={s}>{s}</option>)}</SelectField><Field label="Delivery date" name="delivery_date" type="date" defaultValue={o.delivery_date}/></div><div className="between"><span>Payment received</span><Switch aria-label="Payment received" checked={paid} onCheckedChange={setPaid}/></div></Form></section>;}
function Customers(){const r=useLoad<any[]>('admin/customers');return <><PageTitle title="Customers"/>{r.loading||r.error?<Loading error={r.error} retry={r.reload}/>:!r.data?.length?<Empty icon={Users} title="No customers yet">Registered customers will appear here.</Empty>:<div className="panel table-panel"><Table><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Email</TableHead><TableHead>Phone</TableHead><TableHead>Gura Gold</TableHead></TableRow></TableHeader><TableBody>{r.data.map(u=><TableRow key={u.id}><TableCell>{u.name}</TableCell><TableCell>{u.email}</TableCell><TableCell>{u.phone||'Not added'}</TableCell><TableCell>{u.gold_requested?'Interested':'—'}</TableCell></TableRow>)}</TableBody></Table></div>}</>;}
function ShopSettings(){const {settings,bootstrap}=useShop();return <div className="narrow"><PageTitle title="Shop settings"/><div className="panel"><Form onSave={async(b:any)=>{await api('admin/settings','PATCH',b);await bootstrap();toast.success('Shop settings saved');}}><Field label="Shop name" name="name" defaultValue={settings.name} required/><SelectField label="Shop currency" name="currency" defaultValue={settings.currency}>{['UGX','KRW','USD','KES','TZS','RWF','EUR','GBP'].map(c=><option key={c}>{c}</option>)}</SelectField><p className="muted">Set your currency before adding products.</p><Field label="Delivery fee per order" name="delivery_fee" type="number" min="0" step="0.01" defaultValue={settings.delivery_fee/100} required/><label className="field"><span>Gura Gold membership information</span><textarea name="gold_description" rows={5} maxLength={2000} defaultValue={settings.gold_description} placeholder="Add the benefits and terms when your membership is ready."/></label><p className="muted">Customers can register interest. No membership fees are collected.</p></Form></div></div>;}
