'use client';
import React,{createContext,useContext,useEffect,useRef,useState} from 'react';
import {Home,Grid2X2,Search,UserRound,ShoppingCart,ArrowLeft,ArrowRight,ChevronRight,Settings,Package,Store,Plus,Minus,Trash2,Crown,ShieldCheck,Bell,Globe,LogOut,MapPin,Upload,Camera,ShoppingBag,Shirt,Utensils,House,Smartphone,Sparkles,Sofa,Baby,Volleyball,CookingPot,Puzzle,Car,Dog,NotebookPen,Dumbbell,BookOpen,Gift,ImageIcon,Check,LoaderCircle,Menu} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {NativeSelect} from '@/components/ui/native-select';
import {Switch} from '@/components/ui/switch';
import {Carousel,CarouselContent,CarouselItem,CarouselPrevious,CarouselNext,type CarouselApi} from '@/components/ui/carousel';
import {Toaster,toast} from 'sonner';
import {CATEGORIES,Product,User,Order,CartItem,ShopSettings,money,media} from '@/lib/catalog';
import Admin from './admin';
import {api,setSessionUser,watchSession} from '@/lib/client-api';
export {api} from '@/lib/client-api';
export function go(path:string){window.location.hash=path;window.scrollTo({top:0,behavior:'instant'});}
export function useLoad<T=any>(path:string|null,rev=0){const {user}=useShop();const [data,setData]=useState<T|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[version,reload]=useState(0);useEffect(()=>{let live=true;setData(null);setError('');if(!path){setLoading(false);return;}setLoading(true);api(path).then(d=>{if(live)setData(d);}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[path,rev,version,user?.id,user?.role]);return {data,error,loading,reload:()=>reload(n=>n+1)};}
const Context=createContext<any>(null);export function useShop(){return useContext(Context);}
export function Action({children,onClick,variant='default',className='',disabled=false,...props}:any){const [busy,setBusy]=useState(false);return <Button {...props} className={className} variant={variant} disabled={disabled||busy} onClick={async()=>{setBusy(true);try{await onClick?.();}catch(e:any){toast.error(e.message);}finally{setBusy(false);}}}>{busy?<LoaderCircle className="spin"/>:null}{children}</Button>;}
export function Form({children,onSave,submit='Save changes',className='',after}:any){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <form className={'form '+className} onSubmit={async e=>{e.preventDefault();setError('');setBusy(true);const form=e.currentTarget;try{await onSave(Object.fromEntries(new FormData(form)),form);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>{children}{error&&<p role="alert" className="error">{error}</p>}<Button type="submit" disabled={busy}>{busy?<LoaderCircle className="spin"/>:null}{busy?'Please wait…':submit}</Button>{after}</form>;}
export function Field({label,...props}:any){return <label className="field"><span>{label}</span><input {...props}/></label>;}
export function SelectField({label,children,...props}:any){return <label className="field"><span>{label}</span><NativeSelect {...props}>{children}</NativeSelect></label>;}
export function Empty({icon:Icon=Package,title,children,action}:any){return <div className="empty"><div className="empty-icon"><Icon size={36} strokeWidth={1.5}/></div><h2>{title}</h2><p>{children}</p>{action}</div>;}
export function Loading({error,retry}:any){return error?<div className="load-state"><p role="alert" className="error">{error}</p><Button variant="outline" onClick={retry}>Try again</Button></div>:<div className="load-state" role="status"><LoaderCircle className="spin"/> Loading…</div>;}
export function Photo({src,alt='',className=''}:any){const [failed,setFailed]=useState(false);return src&&!failed?<img className={'product-photo '+className} src={media(src)} alt={alt} loading="lazy" onError={()=>setFailed(true)}/>:<div className={'photo-placeholder '+className} role="img" aria-label={alt||'No photo'}><ImageIcon size={30}/><span>No photo</span></div>;}
export function Status({value}:any){return <span className={'status '+value.toLowerCase().replaceAll(' ','-')}>{value}</span>;}
export function PageTitle({title,back,children}:any){return <div className="page-title"><div>{back&&<Button variant="ghost" size="icon" aria-label="Go back" onClick={()=>go(back)}><ArrowLeft/></Button>}<h1>{title}</h1></div>{children}</div>;}
const tabs=[['home','Home',Home],['category','Category',Grid2X2],['search','Search',Search],['account','Personal info',UserRound],['cart','Cart',ShoppingCart]] as const;
export default function Shop(){
 const [route,setRoute]=useState('home'),[user,setUser]=useState<User|null>(null),[settings,setSettings]=useState<ShopSettings>({name:'GURA',currency:'UGX',delivery_fee:0,gold_description:''}),[needsOwner,setNeedsOwner]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0),[auth,setAuth]=useState(''),[count,setCount]=useState(0);
 const session=useRef<User|null|undefined>(undefined),bootstrapRequest=useRef(0);
 const refresh=()=>setRevision(n=>n+1);const bootstrap=async()=>{
  const request=++bootstrapRequest.current;
  try{const b=await api('bootstrap');if(request!==bootstrapRequest.current)return;
   const previous=session.current;
   if(previous!==undefined&&(previous?.id!==b.user?.id||previous?.role!==b.user?.role)){
    setCount(0);refresh();
    toast.info(b.user?'Your active account is now '+b.user.email+'.':'You are signed out. Sign in again to continue.');
   }
   session.current=b.user;setSessionUser(b.user);setUser(b.user);setError('');setSettings(b.settings);setNeedsOwner(b.needsOwner);setReady(true);
  }catch(e:any){if(request===bootstrapRequest.current)setError(e.message);}
 };
 useEffect(()=>{if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});bootstrap();const stopWatching=watchSession(()=>{void bootstrap();});const listener=()=>setRoute(decodeURI(window.location.hash.slice(1))||'home');listener();window.addEventListener('hashchange',listener);return()=>{window.removeEventListener('hashchange',listener);stopWatching();bootstrapRequest.current++;};},[]);
 useEffect(()=>{let live=true;if(user)api('cart').then(c=>{if(live)setCount(c.reduce((n:number,p:CartItem)=>n+p.cart_quantity,0));}).catch(()=>{});else setCount(0);return()=>{live=false;};},[user?.id,revision]);
 const add=async(p:Product,qty=1)=>{if(!user){setAuth('login');return false;}await api('cart','POST',{product_id:p.id,quantity:qty});refresh();toast.success('Added to your cart');return true;};
 const ctx={user,settings,needsOwner,revision,refresh,bootstrap,setAuth,add};const base=route.split('/')[0];const active=['account','settings','orders','checkout'].includes(base)?(base==='checkout'?'cart':'account'):base==='product'?'home':tabs.some(t=>t[0]===base)?base:'home';
 if(!ready)return <main className="startup"><Brand/><Loading error={error} retry={bootstrap}/></main>;
 return <Context.Provider value={ctx}><Toaster richColors position="top-center"/>{base==='admin'?<Admin key={user?.id||'anonymous'} route={route}/>:<Tabs value={active} onValueChange={v=>go(v)} className="shop-shell">
 <header className="site-header"><button className="brand-button" onClick={()=>go('home')}><Brand/></button><div className="header-actions">{user?.role==='admin'&&<Button variant="outline" onClick={()=>go('admin')}>Manage shop</Button>}{!user&&<Button variant="ghost" onClick={()=>setAuth('login')}>Sign in</Button>}<button className="cart-button" aria-label={`Cart, ${count} items`} onClick={()=>go('cart')}><ShoppingCart/><span>{count}</span></button></div></header>
 <TabsList className="main-nav" aria-label="Main navigation">{tabs.map(([id,label,Icon])=><TabsTrigger className="nav-tab" key={id} value={id}><Icon/><span>{label}</span>{id==='cart'&&count>0&&<b className="nav-count">{count}</b>}</TabsTrigger>)}</TabsList>
 <TabsContent value={active} className="page-content"><div key={route+':'+(user?.id||'anonymous')}>
 {base==='home'?<Catalog/>:base==='category'?<Categories/>:base==='search'?<SearchPage/>:base==='product'?<ProductPage id={route.split('/')[1]}/>:base==='account'?<Account/>:base==='settings'?<AccountSettings/>:base==='orders'?<Orders/>:base==='cart'?<Cart/>:base==='checkout'?<Checkout/>:base==='owner-setup'?<OwnerSetup/>:<Catalog/>}
 </div></TabsContent><footer className="site-footer"><span>© {new Date().getFullYear()} {settings.name} · McLAM Online Shops</span>{needsOwner&&<button onClick={()=>go('owner-setup')}>Set up shop owner</button>}</footer>
 </Tabs>}
 <AuthDialog mode={auth} setMode={setAuth}/></Context.Provider>;
}
export function Brand(){return <div className="brand"><strong>GURA<span>•</span></strong><small>McLAM Online Shops</small></div>;}
function AuthDialog({mode,setMode}:any){const {bootstrap}=useShop();return <Dialog open={!!mode} onOpenChange={v=>!v&&setMode('')}><DialogContent><DialogHeader><DialogTitle>{mode==='register'?'Create your account':'Welcome back'}</DialogTitle><DialogDescription>{mode==='register'?'Save your details and keep track of your orders.':'Sign in to GURA with your email and password.'}</DialogDescription></DialogHeader><Form key={mode} submit={mode==='register'?'Create account':'Sign in'} onSave={async(b:any)=>{await api('auth/'+mode,'POST',b);await bootstrap();setMode('');toast.success(mode==='register'?'Your account is ready':'Signed in');}}>{mode==='register'&&<Field label="Your name" name="name" autoComplete="name" required maxLength={100}/>}<Field label="Email" name="email" type="email" autoComplete="email" required/><Field label={mode==='register'?'Password · at least 6 characters':'Password'} name="password" type="password" minLength={mode==='register'?6:undefined} maxLength={128} autoComplete={mode==='register'?'new-password':'current-password'} required/></Form><button className="text-link" onClick={()=>setMode(mode==='register'?'login':'register')}>{mode==='register'?'Already have an account? Sign in':'New to GURA? Create an account'}</button></DialogContent></Dialog>;}
function SignInPrompt(){const {setAuth}=useShop();return <Empty icon={UserRound} title="Make yourself at home" action={<Button onClick={()=>setAuth('login')}>Sign in / Create account</Button>}>Sign in to save your cart, manage your details, and follow your orders.</Empty>;}
function OwnerSetup(){const {needsOwner,bootstrap,user}=useShop();if(!needsOwner)return <Empty icon={Store} title="Your shop owner is set up" action={<Button onClick={()=>go(user?.role==='admin'?'admin':'account')}>{user?.role==='admin'?'Open owner dashboard':'Go to your account'}</Button>}>Use the owner email and password to sign in.</Empty>;return <div className="narrow"><PageTitle title="Set up your shop" back="home"/><p className="muted mb">Create the owner account to start adding your products.</p><div className="panel"><Form submit="Create owner account" onSave={async(b:any)=>{await api('auth/owner-setup','POST',b);await bootstrap();go('admin');toast.success('Your shop is ready for your first product');}}><Field label="Owner setup code" name="setup_key" type="password" autoComplete="off" required/><Field label="Your name" name="name" autoComplete="name" required/><Field label="Owner email" name="email" type="email" autoComplete="email" required/><Field label="Owner password · at least 10 characters" name="password" type="password" autoComplete="new-password" minLength={10} maxLength={128} required/></Form></div></div>;}
function SearchBox({initial='',onSearch,placeholder='Search all products'}:any){const [value,setValue]=useState(initial);return <form className="search-box" role="search" onSubmit={e=>{e.preventDefault();onSearch(value);}}><Search/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>setValue(e.target.value)}/><button type="submit" aria-label="Search"><ArrowRight/></button></form>;}
function Catalog({initialQuery='',initialCategory='',initialBrand=''}:any){const {settings,revision,user}=useShop();const [q,setQ]=useState(initialQuery),[category,setCategory]=useState(initialCategory),[items,setItems]=useState<Product[]>([]),[more,setMore]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[offset,setOffset]=useState(0),[seed]=useState(()=>Math.floor(Math.random()*1e6));const sentinel=useRef<HTMLDivElement>(null);
 useEffect(()=>{setOffset(0);setItems([]);},[q,category,revision]);
 useEffect(()=>{let live=true;setLoading(true);setError('');api('products?'+new URLSearchParams({q,category,brand:initialBrand,seed:String(seed),offset:String(offset)})).then(d=>{if(live){setItems(prev=>offset===0?d.products:[...prev,...d.products.filter((p:Product)=>!prev.some(x=>x.id===p.id))]);setMore(d.more);}}).catch(e=>live&&setError(e.message)).finally(()=>live&&setLoading(false));return()=>{live=false;};},[q,category,offset,revision,initialBrand,seed]);
 useEffect(()=>{const node=sentinel.current;if(!node||!more||loading||error)return;const observer=new IntersectionObserver(entries=>{if(entries[0].isIntersecting)setOffset(n=>n+24);},{rootMargin:'250px'});observer.observe(node);return()=>observer.disconnect();},[more,loading,error]);
 return <><SearchBox initial={q} onSearch={(v:string)=>{setOffset(0);setQ(v);}}/>{(category||q||initialBrand)&&<div className="results-title"><h1>{category||initialBrand||(q?'Results for “'+q+'”':'All products')}</h1><button className="text-link" onClick={()=>{setCategory('');setQ('');go('home');}}>Clear filters</button></div>}{items.length>0&&<div className="product-grid">{items.map(p=><ProductCard key={p.id} p={p}/>)}</div>}{!loading&&!items.length&&!error&&<Empty icon={ShoppingBag} title={q||category||initialBrand?'No products here yet':'The shelves are waiting'} action={user?.role==='admin'?<Button onClick={()=>go('admin/products/new')}><Plus/> Add your first product</Button>:undefined}>{q?'Try another product name or brand.':category?'New products in this category will appear here.':'Products will appear here as soon as the shop adds them.'}</Empty>}{loading||error?<Loading error={error} retry={()=>{setOffset(0);setQ(q+' ');}}/>:null}<div ref={sentinel}/>{more&&!loading&&<div className="center"><Button variant="outline" onClick={()=>setOffset(n=>n+24)}>Show more products</Button></div>}</>;
}
export function ProductCard({p}: {p:Product}){const {settings,add}=useShop();return <article className="product-card"><button className="product-open" onClick={()=>go('product/'+p.id)}><Photo src={p.image} alt={p.name}/><div className="product-info"><small>{p.brand||p.category}</small><h3>{p.name}</h3><strong>{money(p.price,settings.currency)} <span>/ {p.unit}</span></strong><span className={'stock-note '+(!p.quantity?'sold-out':'')}>{p.quantity?'In stock':'Out of stock'}</span></div></button><Action variant="outline" className="add-card" disabled={!p.quantity} onClick={()=>add(p)}><Plus/> Add to cart</Action></article>;}
const categoryIcons=[Shirt,Utensils,House,Smartphone,Sparkles,Sofa,Baby,Volleyball,CookingPot,Puzzle,Car,Dog,NotebookPen,Dumbbell,BookOpen,Gift];
function Categories(){const [selected,setSelected]=useState('');if(selected)return <><button className="back-link" onClick={()=>setSelected('')}><ArrowLeft/> All categories</button><Catalog initialCategory={selected}/></>;return <><PageTitle title="Categories"/><div className="category-grid">{CATEGORIES.map((c,i)=>{const Icon=categoryIcons[i];return <button key={c} className="category-tile" onClick={()=>setSelected(c)}><span className={'category-icon tone-'+i%6}><Icon/></span><span>{c}</span><ChevronRight size={16}/></button>;})}</div></>;}
function SearchPage(){const {user,revision,setAuth}=useShop();const history=useLoad<any>(user?'history':null,revision);const [query,setQuery]=useState(''),[brand,setBrand]=useState('');if(query||brand)return <Catalog initialQuery={query} initialBrand={brand}/>;return <><PageTitle title="Search"/><SearchBox placeholder="Search products or brands" onSearch={setQuery}/><section className="section"><h2>Your top brands</h2><p className="muted">Based on how often you’ve purchased them.</p>{!user?<div className="soft-empty">Sign in to see your favourite brands. <button className="text-link" onClick={()=>setAuth('login')}>Sign in</button></div>:history.loading||history.error?<Loading error={history.error} retry={history.reload}/>:history.data?.brands.length?<div className="brand-grid">{history.data.brands.map((b:any)=><button key={b.brand} className="brand-tile" onClick={()=>setBrand(b.brand)}><strong>{b.brand}</strong><small>{b.purchases} purchase{b.purchases===1?'':'s'}</small></button>)}</div>:<div className="soft-empty">Your top brands will appear after your first paid order.</div>}</section><section className="section"><h2>Previously bought</h2>{history.data?.products.length?<div className="product-grid">{history.data.products.map((p:Product)=><ProductCard key={p.id} p={p}/>)}</div>:<div className="soft-empty">Your purchased products will appear here for easy reordering.</div>}</section></>;}
function ProductPage({id}:{id:string}){const {settings,add,revision}=useShop(),result=useLoad<Product>('products/'+id,revision);const [quantity,setQuantity]=useState(1),[carousel,setCarousel]=useState<CarouselApi>(),[slide,setSlide]=useState(0),[enlarge,setEnlarge]=useState(false);
 useEffect(()=>{if(!carousel)return;const fn=()=>setSlide(carousel.selectedScrollSnap());fn();carousel.on('select',fn);return()=>{carousel.off('select',fn);};},[carousel]);
 if(!result.data)return <Loading error={result.error} retry={result.reload}/>;const p=result.data,photos=p.images||[];
 return <><PageTitle title="Product details" back="home"/><div className="product-detail"><div><Carousel setApi={setCarousel} opts={{loop:photos.length>1}} className="gallery"><CarouselContent>{photos.length?photos.map((photo,i)=><CarouselItem key={photo.id}><button className="gallery-photo" onClick={()=>setEnlarge(true)} aria-label={`Enlarge photo ${i+1} of ${p.name}`}><Photo src={photo.object_key} alt={`${p.name}, photo ${i+1}`}/></button></CarouselItem>):<CarouselItem><Photo alt={p.name}/></CarouselItem>}</CarouselContent>{photos.length>1&&<><CarouselPrevious className="gallery-prev"/><CarouselNext className="gallery-next"/><span className="photo-counter">{slide+1} / {photos.length}</span></>}</Carousel>{photos.length>1&&<><div className="dots">{photos.map((p,i)=><button key={p.id} className={slide===i?'current':''} aria-label={'Show photo '+(i+1)} onClick={()=>carousel?.scrollTo(i)}/>)}</div><p className="center muted">Swipe left or right for more photos</p></>}</div><div className="product-description"><span className="eyebrow">{p.brand||p.category}</span><h1>{p.name}</h1><p className="big-price">{money(p.price,settings.currency)} <small>/ {p.unit}</small></p><Status value={p.quantity?'In stock':'Out of stock'}/><p className="description">{p.description||'No description added yet.'}</p><div className="quantity-row"><span>Quantity</span><Quantity value={quantity} max={p.quantity} onChange={setQuantity}/></div><small className="muted">{p.quantity} {p.unit} available</small><Action className="wide" disabled={!p.quantity} onClick={()=>add(p,quantity)}><ShoppingCart/> Add to cart</Action><Action variant="outline" className="wide" disabled={!p.quantity} onClick={async()=>{if(await add(p,quantity))go('checkout');}}>Buy now</Action></div></div><Dialog open={enlarge} onOpenChange={setEnlarge}><DialogContent className="lightbox"><DialogHeader><DialogTitle>{p.name} · {slide+1} / {photos.length}</DialogTitle><DialogDescription>Pinch to zoom on mobile, or open the photo for a closer look.</DialogDescription></DialogHeader><a href={media(photos[slide]?.object_key)} target="_blank" rel="noreferrer"><Photo src={photos[slide]?.object_key} alt={p.name}/></a><div className="between"><Button variant="outline" disabled={!photos.length} onClick={()=>carousel?.scrollPrev()}><ArrowLeft/> Previous</Button><Button variant="outline" onClick={()=>carousel?.scrollNext()}>Next <ArrowRight/></Button></div></DialogContent></Dialog></>;
}
function Quantity({value,max,onChange}:any){return <div className="quantity"><Button variant="ghost" size="icon" aria-label="Decrease quantity" disabled={value<=1} onClick={()=>onChange(value-1)}><Minus size={16}/></Button><span>{value}</span><Button variant="ghost" size="icon" aria-label="Increase quantity" disabled={value>=max} onClick={()=>onChange(value+1)}><Plus size={16}/></Button></div>;}
function Account(){const {user,settings,revision,setAuth}=useShop();const orders=useLoad<Order[]>(user?'orders':null,revision);if(!user)return <SignInPrompt/>;return <div className="account-layout"><div className="account-top"><div className="profile-title"><div className="avatar">{user.avatar?<Photo src={user.avatar} alt="Your profile photo"/>:<UserRound size={36}/>}</div><div><h1>{user.name.split(' ')[0]}</h1><span className="muted">{user.role==='admin'?'Shop owner':'Your GURA account'}</span></div></div><Button variant="outline" onClick={()=>go('settings')}><Settings/> Settings</Button></div><button className="gold-card" onClick={()=>go('settings/gold')}><Crown/><div><strong>Gura Gold Account</strong><span>{user.gold_requested?'Membership interest registered':'View membership information'}</span></div><ChevronRight/></button>{user.role==='admin'&&<Button onClick={()=>go('admin')}><Store/> Open owner dashboard</Button>}<section className="section"><div className="between"><h2>My orders</h2><button className="text-link" onClick={()=>go('orders')}>See all <ArrowRight size={16}/></button></div>{orders.loading||orders.error?<Loading error={orders.error} retry={orders.reload}/>:orders.data?.length?<><Carousel opts={{align:'start'}} className="order-carousel"><CarouselContent>{orders.data.slice(0,8).map(o=><CarouselItem key={o.id} className="recent-order"><OrderCard order={o} compact/></CarouselItem>)}</CarouselContent></Carousel><p className="muted center">Swipe left or right to see recent orders</p></>:<Empty title="Your first order starts here" action={<Button variant="outline" onClick={()=>go('home')}>Browse products</Button>}>Your recent orders and their progress will appear here.</Empty>}</section></div>;}
function masked(s:string,kind='name'){if(!s)return 'Not added';if(kind==='email'){const [a,b]=s.split('@');return a.slice(0,3)+'***@'+b;}if(kind==='phone')return s.length>6?s.slice(0,5)+'****'+s.slice(-4):'****';return s.slice(0,4)+'*****';}
function AccountSettings(){const {user,settings,bootstrap}=useShop();const [editing,setEditing]=useState(typeof window!=='undefined'&&window.location.hash.endsWith('/gold')?'gold':''),[deleting,setDeleting]=useState(false),[notifications,setNotifications]=useState(!!user?.notifications);if(!user)return <SignInPrompt/>;const save=async(b:any)=>{await api('profile','PATCH',{...user,...b,notifications:b.notifications??notifications});await bootstrap();setEditing('');toast.success('Settings saved');};
 return <div className="settings-page narrow"><PageTitle title="Settings" back="account"/><section className="panel"><h2>Account details</h2><button className="settings-row" onClick={()=>setEditing('profile')}><UserRound/><span>Name</span><b>{masked(user.name)}</b><ChevronRight/></button><button className="settings-row" onClick={()=>setEditing('password')}><ShieldCheck/><span>Password</span><b>********</b><ChevronRight/></button><button className="settings-row" onClick={()=>setEditing('profile')}><span className="symbol">@</span><span>Email</span><b>{masked(user.email,'email')}</b><ChevronRight/></button><button className="settings-row" onClick={()=>setEditing('profile')}><Smartphone/><span>Phone</span><b>{masked(user.phone,'phone')}</b><ChevronRight/></button><label className="upload-avatar"><Camera size={18}/> Change profile photo<input type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/avif" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{const d=new FormData();d.append('file',f);await api('profile/avatar','POST',d);await bootstrap();toast.success('Photo updated');}catch(e:any){toast.error(e.message);}}}/></label></section>
 <section className="panel"><h2>Delivery details</h2>{[['Recipient',user.recipient],['Address',user.address],['Phone',user.delivery_phone]].map(([label,value])=><button key={label} className="settings-row" onClick={()=>setEditing('delivery')}><MapPin/><span>{label}</span><b>{value||'Add '+label.toLowerCase()}</b><ChevronRight/></button>)}</section>
 <section className="panel"><h2>Memberships</h2><button className="settings-row" onClick={()=>setEditing('gold')}><Crown/><span>Gura Gold Account</span><ChevronRight/></button></section>
 <section className="panel"><h2>Account settings</h2><button className="settings-row" onClick={()=>setEditing('password')}><ShieldCheck/><span>Security and sign in</span><ChevronRight/></button><div className="settings-row"><Bell/><span>Order notifications</span><Switch aria-label="Order notifications" checked={notifications} onCheckedChange={async checked=>{try{await save({notifications:checked});setNotifications(checked);}catch(e:any){toast.error(e.message);}}}/></div><p className="tiny-help">View updates in My orders. Email and push delivery are not connected yet.</p><button className="settings-row" onClick={()=>setEditing('region')}><Globe/><span>Country/Region & Language</span><ChevronRight/></button><button className="settings-row danger" onClick={()=>setDeleting(true)}><Trash2/><span>Delete account</span><ChevronRight/></button><Action variant="ghost" className="settings-row" onClick={async()=>{await api('auth/logout','POST',{});await bootstrap();go('home');}}><LogOut/> Sign out</Action></section>
 <Dialog open={!!editing} onOpenChange={v=>!v&&setEditing('')}><DialogContent><DialogHeader><DialogTitle>{({profile:'Account details',password:'Security and sign in',delivery:'Delivery details',region:'Country/Region & Language',gold:'Gura Gold Account'} as any)[editing]}</DialogTitle><DialogDescription>{editing==='gold'?'Membership information from the shop owner.':'Update your account information below.'}</DialogDescription></DialogHeader>
 {editing==='profile'&&<Form onSave={save}><Field label="Full name" name="name" defaultValue={user.name} required/><Field label="Email" name="email" type="email" defaultValue={user.email} required/><Field label="Phone" name="phone" type="tel" defaultValue={user.phone}/><Field label="Current password (required to change email)" name="current_password" type="password" autoComplete="current-password"/></Form>}
 {editing==='password'&&<Form submit="Change password" onSave={async(b:any)=>{await api('profile/password','POST',b);setEditing('');toast.success('Password changed. Other sessions have been signed out.');}}><Field label="Current password" name="current_password" type="password" autoComplete="current-password" required/><Field label={`New password · at least ${user.role==='admin'?10:6} characters`} name="password" type="password" minLength={user.role==='admin'?10:6} maxLength={128} autoComplete="new-password" required/></Form>}
 {editing==='delivery'&&<Form onSave={save}><DeliveryFields user={user}/></Form>}
 {editing==='region'&&<Form onSave={save}><Field label="Country / Region" name="country" defaultValue={user.country} required/><SelectField label="Language" name="language" defaultValue="en"><option value="en">English</option></SelectField><p className="muted">English is currently available. Your region does not convert the shop’s prices.</p></Form>}
 {editing==='gold'&&<><p className="description">{settings.gold_description||'The shop owner has not announced membership benefits or pricing yet.'}</p><Action disabled={!!user.gold_requested} onClick={async()=>{await api('profile/gold','POST',{});await bootstrap();toast.success('Your interest has been sent to the shop owner');}}>{user.gold_requested?'Interest registered':'Register my interest'}</Action><p className="muted">This does not start a paid membership.</p></>}
 </DialogContent></Dialog>
 <AlertDialog open={deleting} onOpenChange={setDeleting}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete your account?</AlertDialogTitle><AlertDialogDescription>Your profile, saved cart, and sign-in sessions will be removed. Completed order records remain with personal delivery details removed. Open orders must be completed or cancelled first.</AlertDialogDescription></AlertDialogHeader><Form submit="Delete my account" onSave={async(b:any)=>{await api('profile/delete','POST',b);setDeleting(false);await bootstrap();go('home');}}><Field label="Confirm your password" name="password" type="password" autoComplete="current-password" required/></Form><AlertDialogFooter><AlertDialogCancel>Keep my account</AlertDialogCancel></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
function DeliveryFields({user}:any){return <><Field label="Recipient" name="recipient" defaultValue={user.recipient} autoComplete="shipping name" required/><Field label="Delivery address" name="address" defaultValue={user.address} autoComplete="shipping street-address" required/><Field label="Delivery phone" name="delivery_phone" type="tel" defaultValue={user.delivery_phone} autoComplete="shipping tel" required/></>;}
export function OrderCard({order:o,compact=false}: {order:Order;compact?:boolean}){const {add}=useShop();const reorder=async(item:any,checkout=false)=>{const p=await api('products/'+item.product_id);if(await add(p,item.quantity))if(checkout)go('checkout');};return <article className={'order-card '+(compact?'compact':'')}><div className="order-top"><span>#{o.id.slice(0,8).toUpperCase()}</span><Status value={o.status}/></div>{(compact?o.items.slice(0,1):o.items).map(item=><div className="order-item" key={item.id}><Photo src={item.image} alt={item.name}/><div><h3>{item.name}</h3><p>{item.quantity} {item.unit} · {o.paid?'Paid':'Total'} {money(item.price*item.quantity,o.currency)}</p>{!compact&&<div className="order-actions"><Action onClick={()=>reorder(item,true)}>Buy again</Action><Action variant="outline" onClick={()=>reorder(item)}><ShoppingCart/> Add to cart</Action></div>}</div></div>)}{compact&&o.items.length>1&&<small>+ {o.items.length-1} more item(s)</small>}<p className="delivery-date">{o.status==='Delivered'?'Delivered':o.status==='Cancelled'?'Cancelled':'Estimated delivery'}{o.status==='Cancelled'?'':o.delivery_date?' · '+new Date(o.delivery_date+'T12:00:00').toLocaleDateString('en',{day:'numeric',month:'short',year:'numeric'}):' · Awaiting confirmation'}</p>{compact?<Button variant="outline" onClick={()=>go('orders')}>View order</Button>:<div className="order-total"><strong>Order total {money(o.total,o.currency)}</strong><span>{o.paid?'Payment received':'Pay on delivery · Payment pending'}</span></div>}</article>;}
function Orders(){const {user,revision}=useShop();const r=useLoad<Order[]>(user?'orders':null,revision),[filter,setFilter]=useState('All');if(!user)return <SignInPrompt/>;const orders=r.data?.filter(o=>filter==='All'||o.status===filter);return <><PageTitle title="My orders" back="account"/><div className="filter-row">{['All','Pending','On the way','Delivered','Cancelled'].map(s=><Button key={s} variant={filter===s?'default':'outline'} onClick={()=>setFilter(s)}>{s}</Button>)}</div>{r.loading||r.error?<Loading error={r.error} retry={r.reload}/>:orders?.length?<div className="orders-grid">{orders.map(o=><OrderCard key={o.id} order={o}/>)}</div>:<Empty title="No orders to show">Orders matching this view will appear here.</Empty>}</>;}
function Cart(){const {user,revision,refresh,settings}=useShop(),r=useLoad<CartItem[]>(user?'cart':null,revision);if(!user)return <SignInPrompt/>;if(r.loading||r.error)return <Loading error={r.error} retry={r.reload}/>;const cart=r.data||[],total=cart.reduce((a,p)=>a+p.price*p.cart_quantity,0);return <><PageTitle title="Your cart"/><p className="muted mb">{cart.length} item{cart.length===1?'':'s'} in your cart</p>{!cart.length?<Empty icon={ShoppingCart} title="Your cart is waiting" action={<Button onClick={()=>go('home')}>Browse products</Button>}>Add something you like, and it will appear here.</Empty>:<div className="cart-layout"><div className="cart-items">{cart.map(p=><article className="cart-item" key={p.id}><button onClick={()=>go('product/'+p.id)}><Photo src={p.image} alt={p.name}/></button><div><h3>{p.name}</h3><strong>{money(p.price,settings.currency)} / {p.unit}</strong><p className="stock-note">{p.active?p.quantity+' '+p.unit+' available':'No longer available'}</p><Quantity value={p.cart_quantity} max={p.quantity} onChange={async(n:number)=>{try{await api('cart','POST',{product_id:p.id,quantity:n,replace:true});refresh();}catch(e:any){toast.error(e.message);}}}/></div><Action variant="ghost" aria-label={'Remove '+p.name} onClick={async()=>{await api('cart/'+p.id,'DELETE');refresh();}}><Trash2/></Action></article>)}</div><div className="panel summary"><h2>Order summary</h2><Summary subtotal={total}/><Button className="wide" onClick={()=>go('checkout')} disabled={cart.some(p=>!p.active||p.cart_quantity>p.quantity)}>Proceed to checkout <ArrowRight/></Button><p className="muted">Pay on delivery</p></div></div>}</>;}
function Summary({subtotal}:any){const {settings}=useShop();return <div className="summary-lines"><div><span>Subtotal</span><span>{money(subtotal,settings.currency)}</span></div><div><span>Delivery</span><span>{money(settings.delivery_fee,settings.currency)}</span></div><div className="total"><strong>Total</strong><strong>{money(subtotal+settings.delivery_fee,settings.currency)}</strong></div></div>;}
function Checkout(){const {user,revision,refresh}=useShop(),r=useLoad<CartItem[]>(user?'cart':null,revision),[requestId]=useState(()=>crypto.randomUUID());if(!user)return <SignInPrompt/>;if(r.loading||r.error)return <Loading error={r.error} retry={r.reload}/>;const items=r.data||[];if(!items.length)return <Empty title="Your cart is empty" action={<Button onClick={()=>go('home')}>Browse products</Button>}>Add products before checking out.</Empty>;return <div className="narrow"><PageTitle title="Checkout" back="cart"/><section className="panel"><h2>Delivery details</h2><Form submit="Place order · Pay on delivery" onSave={async(b:any)=>{await api('orders','POST',{...b,phone:b.delivery_phone,request_id:requestId});refresh();go('orders');toast.success('Your order has been placed');}}><DeliveryFields user={user}/><Summary subtotal={items.reduce((a,p)=>a+p.price*p.cart_quantity,0)}/><div className="payment-choice"><Check/> Pay on delivery</div><p className="muted">The shop owner will confirm your order and delivery date.</p></Form></section></div>;}
